// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/trpc/*": {
    params: {
      "*": string;
    };
  };
  "/api/docs/*": {
    params: {
      "*": string;
    };
  };
  "/landing": {
    params: {};
  };
  "/features": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/guide": {
    params: {};
  };
  "/donate": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/onboarding": {
    params: {};
  };
  "/dashboard/billing": {
    params: {};
  };
  "/dashboard/messages": {
    params: {};
  };
  "/dashboard/conversations": {
    params: {};
  };
  "/dashboard/media": {
    params: {};
  };
  "/dashboard/calls": {
    params: {};
  };
  "/dashboard/calls/:callId": {
    params: {
      "callId": string;
    };
  };
  "/dashboard/theater": {
    params: {};
  };
  "/dashboard/digests": {
    params: {};
  };
  "/dashboard/events": {
    params: {};
  };
  "/dashboard/timeline": {
    params: {};
  };
  "/dashboard/announcements": {
    params: {};
  };
  "/dashboard/shopping-lists": {
    params: {};
  };
  "/dashboard/settings": {
    params: {};
  };
  "/dashboard/family/:familyId": {
    params: {
      "familyId": string;
    };
  };
  "/dashboard/members": {
    params: {};
  };
  "/family-invite/:token": {
    params: {
      "token": string;
    };
  };
  "/share/timeline/:shareToken": {
    params: {
      "shareToken": string;
    };
  };
  "/designSystem": {
    params: {};
  };
  "/docs": {
    params: {};
  };
  "/admin/families": {
    params: {};
  };
  "/admin/clearance-levels": {
    params: {};
  };
  "/admin/donations": {
    params: {};
  };
  "/admin/moderation": {
    params: {};
  };
  "/admin/integrations": {
    params: {};
  };
  "/admin/maintenance": {
    params: {};
  };
  "/admin/pin-messages": {
    params: {};
  };
  "/admin/archive-threads": {
    params: {};
  };
  "/admin/billing/plans": {
    params: {};
  };
  "/admin/photo-digitization": {
    params: {};
  };
  "/admin/inquiries": {
    params: {};
  };
  "/dev/test-data": {
    params: {};
  };
  "/auth/github": {
    params: {};
  };
  "/auth/github/callback": {
    params: {};
  };
  "/auth/google": {
    params: {};
  };
  "/auth/google/callback": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/trpc/*" | "/api/docs/*" | "/landing" | "/features" | "/pricing" | "/guide" | "/donate" | "/login" | "/signup" | "/dashboard" | "/dashboard/onboarding" | "/dashboard/billing" | "/dashboard/messages" | "/dashboard/conversations" | "/dashboard/media" | "/dashboard/calls" | "/dashboard/calls/:callId" | "/dashboard/theater" | "/dashboard/digests" | "/dashboard/events" | "/dashboard/timeline" | "/dashboard/announcements" | "/dashboard/shopping-lists" | "/dashboard/settings" | "/dashboard/family/:familyId" | "/dashboard/members" | "/family-invite/:token" | "/share/timeline/:shareToken" | "/designSystem" | "/docs" | "/admin/families" | "/admin/clearance-levels" | "/admin/donations" | "/admin/moderation" | "/admin/integrations" | "/admin/maintenance" | "/admin/pin-messages" | "/admin/archive-threads" | "/admin/billing/plans" | "/admin/photo-digitization" | "/admin/inquiries" | "/dev/test-data" | "/auth/github" | "/auth/github/callback" | "/auth/google" | "/auth/google/callback" | "/*";
  };
  "routes/api.trpc.$.tsx": {
    id: "routes/api.trpc.$";
    page: "/api/trpc/*";
  };
  "routes/api.docs.$.tsx": {
    id: "routes/api.docs.$";
    page: "/api/docs/*";
  };
  "routes/root.tsx": {
    id: "routes/root";
    page: "/" | "/landing" | "/features" | "/pricing" | "/guide" | "/donate" | "/login" | "/signup" | "/dashboard" | "/dashboard/onboarding" | "/dashboard/billing" | "/dashboard/messages" | "/dashboard/conversations" | "/dashboard/media" | "/dashboard/calls" | "/dashboard/calls/:callId" | "/dashboard/theater" | "/dashboard/digests" | "/dashboard/events" | "/dashboard/timeline" | "/dashboard/announcements" | "/dashboard/shopping-lists" | "/dashboard/settings" | "/dashboard/family/:familyId" | "/dashboard/members" | "/family-invite/:token" | "/share/timeline/:shareToken" | "/designSystem" | "/docs" | "/admin/families" | "/admin/clearance-levels" | "/admin/donations" | "/admin/moderation" | "/admin/integrations" | "/admin/maintenance" | "/admin/pin-messages" | "/admin/archive-threads" | "/admin/billing/plans" | "/admin/photo-digitization" | "/admin/inquiries" | "/dev/test-data" | "/auth/github" | "/auth/github/callback" | "/auth/google" | "/auth/google/callback" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/landing.tsx": {
    id: "routes/landing";
    page: "/landing";
  };
  "routes/features.tsx": {
    id: "routes/features";
    page: "/features";
  };
  "routes/pricing.tsx": {
    id: "routes/pricing";
    page: "/pricing";
  };
  "routes/guide.tsx": {
    id: "routes/guide";
    page: "/guide";
  };
  "routes/donate.tsx": {
    id: "routes/donate";
    page: "/donate";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/dashboard/onboarding.tsx": {
    id: "routes/dashboard/onboarding";
    page: "/dashboard/onboarding";
  };
  "routes/dashboard/billing.tsx": {
    id: "routes/dashboard/billing";
    page: "/dashboard/billing";
  };
  "routes/dashboard/messages.tsx": {
    id: "routes/dashboard/messages";
    page: "/dashboard/messages";
  };
  "routes/dashboard/conversations.tsx": {
    id: "routes/dashboard/conversations";
    page: "/dashboard/conversations";
  };
  "routes/dashboard/media.tsx": {
    id: "routes/dashboard/media";
    page: "/dashboard/media";
  };
  "routes/dashboard/calls.tsx": {
    id: "routes/dashboard/calls";
    page: "/dashboard/calls";
  };
  "routes/dashboard/calls/$callId.tsx": {
    id: "routes/dashboard/calls/$callId";
    page: "/dashboard/calls/:callId";
  };
  "routes/dashboard/theater.tsx": {
    id: "routes/dashboard/theater";
    page: "/dashboard/theater";
  };
  "routes/dashboard/digests.tsx": {
    id: "routes/dashboard/digests";
    page: "/dashboard/digests";
  };
  "routes/dashboard/events.tsx": {
    id: "routes/dashboard/events";
    page: "/dashboard/events";
  };
  "routes/dashboard/timeline.tsx": {
    id: "routes/dashboard/timeline";
    page: "/dashboard/timeline";
  };
  "routes/dashboard/announcements.tsx": {
    id: "routes/dashboard/announcements";
    page: "/dashboard/announcements";
  };
  "routes/dashboard/shopping-lists.tsx": {
    id: "routes/dashboard/shopping-lists";
    page: "/dashboard/shopping-lists";
  };
  "routes/dashboard/settings.tsx": {
    id: "routes/dashboard/settings";
    page: "/dashboard/settings";
  };
  "routes/dashboard/family/$familyId.tsx": {
    id: "routes/dashboard/family/$familyId";
    page: "/dashboard/family/:familyId";
  };
  "routes/dashboard/members.tsx": {
    id: "routes/dashboard/members";
    page: "/dashboard/members";
  };
  "routes/family-invite/$token.tsx": {
    id: "routes/family-invite/$token";
    page: "/family-invite/:token";
  };
  "routes/share/timeline.$shareToken.tsx": {
    id: "routes/share/timeline.$shareToken";
    page: "/share/timeline/:shareToken";
  };
  "routes/designSystem.tsx": {
    id: "routes/designSystem";
    page: "/designSystem";
  };
  "routes/docs.tsx": {
    id: "routes/docs";
    page: "/docs";
  };
  "routes/admin/families.tsx": {
    id: "routes/admin/families";
    page: "/admin/families";
  };
  "routes/admin/clearance-levels.tsx": {
    id: "routes/admin/clearance-levels";
    page: "/admin/clearance-levels";
  };
  "routes/admin/donations.tsx": {
    id: "routes/admin/donations";
    page: "/admin/donations";
  };
  "routes/admin/moderation.tsx": {
    id: "routes/admin/moderation";
    page: "/admin/moderation";
  };
  "routes/admin/integrations.tsx": {
    id: "routes/admin/integrations";
    page: "/admin/integrations";
  };
  "routes/admin/maintenance.tsx": {
    id: "routes/admin/maintenance";
    page: "/admin/maintenance";
  };
  "routes/admin/pin-messages.tsx": {
    id: "routes/admin/pin-messages";
    page: "/admin/pin-messages";
  };
  "routes/admin/archive-threads.tsx": {
    id: "routes/admin/archive-threads";
    page: "/admin/archive-threads";
  };
  "routes/admin/billing/plans.tsx": {
    id: "routes/admin/billing/plans";
    page: "/admin/billing/plans";
  };
  "routes/admin/photo-digitization.tsx": {
    id: "routes/admin/photo-digitization";
    page: "/admin/photo-digitization";
  };
  "routes/admin/inquiries.tsx": {
    id: "routes/admin/inquiries";
    page: "/admin/inquiries";
  };
  "routes/dev.test-data.tsx": {
    id: "routes/dev.test-data";
    page: "/dev/test-data";
  };
  "routes/auth/github.tsx": {
    id: "routes/auth/github";
    page: "/auth/github";
  };
  "routes/auth/github.callback.tsx": {
    id: "routes/auth/github.callback";
    page: "/auth/github/callback";
  };
  "routes/auth/google.tsx": {
    id: "routes/auth/google";
    page: "/auth/google";
  };
  "routes/auth/google.callback.tsx": {
    id: "routes/auth/google.callback";
    page: "/auth/google/callback";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api.trpc.$": typeof import("./app/routes/api.trpc.$.tsx");
  "routes/api.docs.$": typeof import("./app/routes/api.docs.$.tsx");
  "routes/root": typeof import("./app/routes/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/landing": typeof import("./app/routes/landing.tsx");
  "routes/features": typeof import("./app/routes/features.tsx");
  "routes/pricing": typeof import("./app/routes/pricing.tsx");
  "routes/guide": typeof import("./app/routes/guide.tsx");
  "routes/donate": typeof import("./app/routes/donate.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/dashboard/onboarding": typeof import("./app/routes/dashboard/onboarding.tsx");
  "routes/dashboard/billing": typeof import("./app/routes/dashboard/billing.tsx");
  "routes/dashboard/messages": typeof import("./app/routes/dashboard/messages.tsx");
  "routes/dashboard/conversations": typeof import("./app/routes/dashboard/conversations.tsx");
  "routes/dashboard/media": typeof import("./app/routes/dashboard/media.tsx");
  "routes/dashboard/calls": typeof import("./app/routes/dashboard/calls.tsx");
  "routes/dashboard/calls/$callId": typeof import("./app/routes/dashboard/calls/$callId.tsx");
  "routes/dashboard/theater": typeof import("./app/routes/dashboard/theater.tsx");
  "routes/dashboard/digests": typeof import("./app/routes/dashboard/digests.tsx");
  "routes/dashboard/events": typeof import("./app/routes/dashboard/events.tsx");
  "routes/dashboard/timeline": typeof import("./app/routes/dashboard/timeline.tsx");
  "routes/dashboard/announcements": typeof import("./app/routes/dashboard/announcements.tsx");
  "routes/dashboard/shopping-lists": typeof import("./app/routes/dashboard/shopping-lists.tsx");
  "routes/dashboard/settings": typeof import("./app/routes/dashboard/settings.tsx");
  "routes/dashboard/family/$familyId": typeof import("./app/routes/dashboard/family/$familyId.tsx");
  "routes/dashboard/members": typeof import("./app/routes/dashboard/members.tsx");
  "routes/family-invite/$token": typeof import("./app/routes/family-invite/$token.tsx");
  "routes/share/timeline.$shareToken": typeof import("./app/routes/share/timeline.$shareToken.tsx");
  "routes/designSystem": typeof import("./app/routes/designSystem.tsx");
  "routes/docs": typeof import("./app/routes/docs.tsx");
  "routes/admin/families": typeof import("./app/routes/admin/families.tsx");
  "routes/admin/clearance-levels": typeof import("./app/routes/admin/clearance-levels.tsx");
  "routes/admin/donations": typeof import("./app/routes/admin/donations.tsx");
  "routes/admin/moderation": typeof import("./app/routes/admin/moderation.tsx");
  "routes/admin/integrations": typeof import("./app/routes/admin/integrations.tsx");
  "routes/admin/maintenance": typeof import("./app/routes/admin/maintenance.tsx");
  "routes/admin/pin-messages": typeof import("./app/routes/admin/pin-messages.tsx");
  "routes/admin/archive-threads": typeof import("./app/routes/admin/archive-threads.tsx");
  "routes/admin/billing/plans": typeof import("./app/routes/admin/billing/plans.tsx");
  "routes/admin/photo-digitization": typeof import("./app/routes/admin/photo-digitization.tsx");
  "routes/admin/inquiries": typeof import("./app/routes/admin/inquiries.tsx");
  "routes/dev.test-data": typeof import("./app/routes/dev.test-data.tsx");
  "routes/auth/github": typeof import("./app/routes/auth/github.tsx");
  "routes/auth/github.callback": typeof import("./app/routes/auth/github.callback.tsx");
  "routes/auth/google": typeof import("./app/routes/auth/google.tsx");
  "routes/auth/google.callback": typeof import("./app/routes/auth/google.callback.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};